site_name: My Docs
site_url: https://hayao-sato.github.io/action-tester/

docs_dir: src

theme:
  name: material
  language: ja

nav:
  - backend: "!include ../backend/mkdocs.yml"
  - è¨­è¨ˆ: "functions/index.md"
  - specs:
      - backend: "spec/api-swagger.md"
      - old: "spec/api-old-swagger.md"

plugins:
  - monorepo
  - swagger-ui-tag

markdown_extensions:
  - pymdownx.superfences:
      # ğŸ‘‡ ã“ã®è¨­å®šã‚’è¿½åŠ ã™ã‚‹
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
